version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka:3.5
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper

  order-service:
    build: ./order-service
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    ports:
      - "8080:8080"

  inventory-service:
    build: ./inventory-service
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092

  notification-service:
    build: ./notification-service
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092 