name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [order-service, inventory-service, notification-service]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: |
          cd ${{ matrix.service }}
          go build -v ./...
      - name: Test
        run: |
          cd ${{ matrix.service }}
          go test -v ./...
      - name: Vet
        run: |
          cd ${{ matrix.service }}
          go vet ./...
      - name: Fmt
        run: |
          cd ${{ matrix.service }}
          test -z "$(gofmt -l .)" || (echo "Code is not gofmt-ed" && exit 1)

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test-lint
    strategy:
      matrix:
        service: [order-service, inventory-service, notification-service]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          file: ${{ matrix.service }}/Dockerfile
          push: false
          tags: ${{ matrix.service }}:ci 